baseURL = "http://heartoftheearth.me/"
DefaultContentLanguage = "en" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "en-us"
title = "維蘇威曼波"
copyright = "2023-2024 司苔拉"
theme = "diary"
# googleAnalytics = "UA-123-45"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = "水也不要消失在水中。"
enableGitalk = false
enableGiscus = false
enableUtterances = true
favicon = "/images/goddess.png"

# Microsoft Clarity (https://clarity.microsoft.com/) is a free user behavior recording and analytics tool
clarity = "abcdefghzd"

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "My Blog" # will set 'og:site_name'
description = "My HomePage Description"  # will set 'og:description'

[params.gitalk]
  owner = "user"
  repo = "repo name"
  client_id = "your client id"
  client_secret = "your client secret"
[taxonomies]
   tag = "tags"
   category = "categories"

[params.utterances]
repo = "aphrodite423/aphrodite423.github.io"
term = "pathname"
label = "Comment"
theme = "github-light"

# Please visit https://giscus.app/ to generate settings.
[params.giscus]
    data_repo="username/repo"
    data_repo_id="**************************"    
    data_category="General"
    data_category_id="*********************"
    data_mapping="pathname"
    data_strict="0"
    data_reactions_enabled="1"
    data_emit_metadata="0"
    data_input_position="bottom"
    data_theme="preferred_color_scheme"
    data_lang="en"
    crossorigin="anonymous"


[[menu.main]]
url = "/categories"
name = "分類 · Categories"
weight = 2
[[menu.main]]
url = "/tags"
name = "標籤 · Tags"
weight = 3
[[menu.main]]
url = "/posts"
name = "歸檔 · Archive"
weight = 1
[[menu.main]]
url = "/about"
name = "關於 · About"
weight = 4
[[menu.main]]
url = "/friends"
name = "朋友們 · Friends"
weight = 5
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 6
[[menu.main]]
url = "/search"
name = "搜索 · Search"
weight = 7

[outputs]
home = ["HTML", "RSS", "JSON"]